openapi: 3.0.0
info:
  title: Student API
  version: 1.0.0
  description: API for managing student records
paths:
  /api/students:
    get:
      summary: Get all students
      responses:
        '200':
          description: A list of students
    post:
      summary: Add a new student
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Student'
      responses:
        '201':
          description: Created

  /api/students/{id}:
    get:
      summary: Get student by ID
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
      responses:
        '200':
          description: Student found
    put:
      summary: Update student by ID
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Student'
      responses:
        '200':
          description: Student updated
    delete:
      summary: Delete student by ID
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
      responses:
        '200':
          description: Student deleted

components:
  schemas:
    Student:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        email:
          type: string
        course:
          type: string
